Verify services pages are displayed correctly
CodeLinkIO/codelink-website-automation pull request #4
Opened 2024-01-09 02:45 UTC by ThaoThaoTran

This PR is to verify all links and pages are displayed correctly when navigating to it

2024-01-10 07:21 UTC, chiivv requested changes

2024-01-10 07:21 UTC, chiivv commented on src/Codelink_Website/core/testcases/ServicesTest.java
> +        homePage.selectItemInHomeBar("Artificial Intelligence & Machine Learning");
[CLARIFICATION] What is the rationale behind having distinct logging mechanisms here, `log.info` and `logInfo`?

2024-01-10 07:21 UTC, chiivv commented on src/Codelink_Website/core/pageObjects/HomePage.java
> +    }
```suggestion
    public void selectHomeBar(String homeBar) {
        waitForElementVisible(driver, ServicesUI.DYNAMIC_BUTTON_HOME_BAR, homeBar);
        hoverMouseToElement(driver, ServicesUI.DYNAMIC_BUTTON_HOME_BAR, homeBar);
    }
```

2024-01-10 07:26 UTC, chiivv commented on src/Codelink_Website/core/testcases/ServicesTest.java
> +        Assert.assertEquals(homePage.getPageURL(driver), GlobalConstants.SOFTWARE_DEVELOPMENT_PAGE);
[BLOCKER] I have a concern regarding the test case design and page structure. It seems we are leaning towards adopting the Page Object Model. If that's the case, there might be additional considerations we need to address
- Add new pages under src/Codelink_Website/core/pageObjects
```
public class softwareDevelopmentPage
    public void verifyTitle();
    public void verifyUrl();
```
- Update validations in test case
```
homePage.selectItemInHomeBar("Software Development");
softwareDevelopmentPage.waitForPageLoad();
softwareDevelopmentPage.verifyTitle();
softwareDevelopmentPage.verifyUrl();

```

2024-01-18 10:25 UTC, chiivv requested changes

2024-01-18 10:25 UTC, chiivv commented on src/Codelink_Website/core/interfaces/ServicesUI.java
> +    public static final String DYNAMIC_BUTTON_SELECT_HOME_BAR="xpath=//div[@class='DesktopMenuExtension-module--list--i50hg']//h6[text()='%s']";
[BLOCKER] Looks like they are dynamic web elements. We might need to rely on the fixed part in class name, e.g:  `xpath=//div[contains(@class, 'HeaderV2-module--right-container-desktop')]//span[text()='%s']`

2024-01-18 10:25 UTC, chiivv commented on src/Codelink_Website/core/pageObjects/CommonFunctionsPage.java
> +    }
[SUGGESTION] These functions seem specifically applicable to the Home page. If that's the case, please move them to the Home page

2024-01-18 10:25 UTC, chiivv commented on src/Codelink_Website/core/testcases/ServicesTest.java
> +        Assert.assertEquals(commonFunctionsPage.getPageURL(driver), GlobalConstants.ARTIFICIAL_INTELLIGENCE_PAGE);
[BLOCKER] commonFunctionsPage is not an actual page. The best practices should be creating separate pages that I mentioned in the previous review. https://github.com/CodeLinkIO/codelink-website-automation/pull/4#discussion_r1446976697

2024-01-24 05:10 UTC, chiivv approved these changes

2024-01-25 02:42 UTC, PhuongMaiAutomation approved these changes

2024-01-25 02:42 UTC, merged