Contact Us Flow-Send Message
CodeLinkIO/codelink-website-automation pull request #5
Opened 2024-01-18 01:02 UTC by PhuongMaiAutomation

2024-01-18 10:42 UTC, chiivv requested changes
One question: Are the images attached in this PR actively utilized for the current tests within the scope of this PR?

2024-01-18 10:42 UTC, chiivv commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +
[BLOCKER] `DataFakerHelpers` should be defined once

2024-01-18 10:42 UTC, chiivv commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +        sleepInSecond(GlobalConstants.SEND_EMAIL_TIMEOUT);
[CLARIFICATION] We should avoid implicit wait like this. Can we use an explicit wait in this case?

2024-01-18 10:42 UTC, chiivv commented on src/Codelink_Website/core/ultilities/GMail.java
> +
```suggestion
    public static boolean isEmailContentMeetExpectation(String toEmail, String subject, List<String> listOfExpectedContents) {
        String emailContent = getEmailBody(toEmail, subject);
        for (String content : listOfExpectedContents) {
            if (!emailContent.contains(content)) {
                return false;
            }
        }
        return true;
    }

```

2024-01-18 10:42 UTC, chiivv commented on src/Codelink_Website/core/ultilities/GMail.java
> +
Also, we might need a logging here to check why it's failed, something like
`Actual result: emailContent != Expected result: listOfExpectedContents`

2024-01-23 17:06 UTC, phuquy-git requested changes
Look good to me

2024-01-23 17:06 UTC, phuquy-git commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +        sleepInSecond(GlobalConstants.SEND_EMAIL_TIMEOUT);
[SUGESTION] In case using `for loop` to retry verifying the email content, please add this logic in the Gmail class, so that we can reuse this method for other classes.

2024-02-07 08:12 UTC, PhuongMaiAutomation commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +
fixed

2024-02-07 08:12 UTC, PhuongMaiAutomation commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +        sleepInSecond(GlobalConstants.SEND_EMAIL_TIMEOUT);
fixed

2024-02-07 08:12 UTC, PhuongMaiAutomation commented on src/Codelink_Website/core/ultilities/GMail.java
> +
fixed

2024-02-07 09:06 UTC, chiivv commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +
@PhuongMaiAutomation I mean we should implement something like
```
dataFakerHelpers = DataFakerHelpers();

dataFakerHelpers.getFaker().name().firstName();
```

2024-02-07 09:08 UTC, chiivv requested changes
@PhuongMaiAutomation One comment and please resolve conflicts

2024-02-17 10:50 UTC, PhuongMaiAutomation commented on src/Codelink_Website/core/testcases/ContactUsTest.java
> +
Can you help explain more? I used a static method getDataFaker(), so we do not need to initialize when calling in class.

2024-02-19 08:21 UTC, chiivv approved these changes

2024-02-19 12:50 UTC, phuquy-git approved these changes

2024-02-19 14:58 UTC, merged